name: First Workflow

on:
  push

jobs:
  meu-job-de-teste1:
    runs-on: ubuntu-latest

    steps:
      - name: Diga Ola
        run: echo "Ola Mundo"

      - name: show dir
        run: pwd

      - name: Listar arquivos
        run: ls -la
